
name: Simple Deployment Pipeline

on:
  push:
      branches-ignore:
        - main
      
jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    name: "Simple Deployment to Vercel Example"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Lint check
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deploy Branch to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: .next
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: .next
